import type { IconName } from '../components/AppIcons';
import type { AppId } from './types';
import { cv } from '../data/portfolio';

export interface AppMeta {
  id: AppId;
  /** Name shown bold in the menu bar when focused */
  menuName: string;
  /** Default window title */
  title: string;
  /** Dock tooltip */
  dockLabel: string;
  icon: IconName;
  size: { w: number; h: number };
  min: { w: number; h: number };
  /** Window chrome is always dark (Xcode, Terminal, Slides) */
  darkChrome?: boolean;
  /** Title bar is part of the content (no separate bar) */
  seamless?: boolean;
}

export const APPS: Record<AppId, AppMeta> = {
  about: {
    id: 'about',
    menuName: 'Finder',
    title: 'About This Portfolio',
    dockLabel: 'Finder — About Me',
    icon: 'finder',
    size: { w: 420, h: 540 },
    min: { w: 320, h: 360 },
  },
  safari: {
    id: 'safari',
    menuName: 'Safari',
    title: 'Start Page',
    dockLabel: 'Safari',
    icon: 'safari',
    size: { w: 720, h: 470 },
    min: { w: 380, h: 300 },
    seamless: true,
  },
  notes: {
    id: 'notes',
    menuName: 'Notes',
    title: 'Notes',
    dockLabel: 'Notes',
    icon: 'notes',
    size: { w: 960, h: 580 },
    min: { w: 360, h: 340 },
    seamless: true,
  },
  slides: {
    id: 'slides',
    menuName: 'PowerPoint',
    title: 'Achievements.pptx — My Journey',
    dockLabel: 'Achievements Deck',
    icon: 'slides',
    size: { w: 760, h: 490 },
    min: { w: 420, h: 300 },
    darkChrome: true,
  },
  xcode: {
    id: 'xcode',
    menuName: 'Xcode',
    title: 'Portfolio',
    dockLabel: 'Xcode — My Portfolio',
    icon: 'xcode',
    size: { w: 1060, h: 600 },
    min: { w: 560, h: 380 },
    darkChrome: true,
    seamless: true,
  },
  mail: {
    id: 'mail',
    menuName: 'Mail',
    title: 'Mail',
    dockLabel: 'Mail — Contact Me',
    icon: 'mail',
    size: { w: 1040, h: 640 },
    min: { w: 360, h: 420 },
    seamless: true,
  },
  settings: {
    id: 'settings',
    menuName: 'System Settings',
    title: 'System Settings',
    dockLabel: 'System Settings',
    icon: 'settings',
    size: { w: 780, h: 560 },
    min: { w: 380, h: 360 },
    seamless: true,
  },
  terminal: {
    id: 'terminal',
    menuName: 'Terminal',
    title: 'ahamed — zsh — 80×24',
    dockLabel: 'Terminal',
    icon: 'terminal',
    size: { w: 640, h: 400 },
    min: { w: 340, h: 240 },
    darkChrome: true,
  },
  finder: {
    id: 'finder',
    menuName: 'Finder',
    title: 'Finder',
    dockLabel: 'Finder',
    icon: 'folder',
    size: { w: 860, h: 520 },
    min: { w: 440, h: 320 },
  },
  photos: {
    id: 'photos',
    menuName: 'Photos',
    title: 'Photos',
    dockLabel: 'Photos',
    icon: 'photos',
    size: { w: 960, h: 620 },
    min: { w: 400, h: 340 },
    seamless: true,
  },
  messages: {
    id: 'messages',
    menuName: 'Messages',
    title: 'Messages',
    dockLabel: 'Messages — Text Me',
    icon: 'messages',
    size: { w: 860, h: 580 },
    min: { w: 380, h: 340 },
  },
  calendar: {
    id: 'calendar',
    menuName: 'Calendar',
    title: 'Calendar',
    dockLabel: 'Calendar',
    icon: 'calendar',
    size: { w: 980, h: 620 },
    min: { w: 360, h: 400 },
    seamless: true,
  },
  music: {
    id: 'music',
    menuName: 'Music',
    title: 'Music',
    dockLabel: 'Music',
    icon: 'music',
    size: { w: 980, h: 620 },
    min: { w: 380, h: 420 },
    seamless: true,
  },
  reminders: {
    id: 'reminders',
    menuName: 'Reminders',
    title: 'Reminders',
    dockLabel: 'Reminders',
    icon: 'reminders',
    size: { w: 860, h: 580 },
    min: { w: 360, h: 360 },
    seamless: true,
  },
  maps: {
    id: 'maps',
    menuName: 'Maps',
    title: 'Maps — Kandy, Sri Lanka',
    dockLabel: 'Maps',
    icon: 'maps',
    size: { w: 900, h: 580 },
    min: { w: 380, h: 340 },
  },
  google: {
    id: 'google',
    menuName: 'Google',
    title: 'Google',
    dockLabel: 'Google',
    icon: 'google',
    size: { w: 760, h: 500 },
    min: { w: 360, h: 320 },
  },
  calculator: {
    id: 'calculator',
    menuName: 'Calculator',
    title: 'Calculator',
    dockLabel: 'Calculator',
    icon: 'calculator',
    size: { w: 240, h: 392 },
    min: { w: 220, h: 340 },
    darkChrome: true,
    seamless: true,
  },
  clock: {
    id: 'clock',
    menuName: 'Clock',
    title: 'Clock',
    dockLabel: 'Clock',
    icon: 'clock',
    size: { w: 760, h: 520 },
    min: { w: 360, h: 380 },
    darkChrome: true,
    seamless: true,
  },
  contacts: {
    id: 'contacts',
    menuName: 'Contacts',
    title: 'Contacts',
    dockLabel: 'Contacts',
    icon: 'contacts',
    size: { w: 900, h: 560 },
    min: { w: 360, h: 380 },
    seamless: true,
  },
  camera: {
    id: 'camera',
    menuName: 'Camera',
    title: 'Camera',
    dockLabel: 'Camera',
    icon: 'camera',
    size: { w: 720, h: 520 },
    min: { w: 360, h: 320 },
    darkChrome: true,
  },
  voicememos: {
    id: 'voicememos',
    menuName: 'Voice Memos',
    title: 'Voice Memos',
    dockLabel: 'Voice Memos',
    icon: 'voicememos',
    size: { w: 820, h: 560 },
    min: { w: 360, h: 380 },
  },
  measure: {
    id: 'measure',
    menuName: 'Measure',
    title: 'Measure',
    dockLabel: 'Measure',
    icon: 'measure',
    size: { w: 640, h: 440 },
    min: { w: 340, h: 300 },
  },
  findmy: {
    id: 'findmy',
    menuName: 'Find My',
    title: 'Find My',
    dockLabel: 'Find My',
    icon: 'findmy',
    size: { w: 900, h: 560 },
    min: { w: 380, h: 360 },
  },
  home: {
    id: 'home',
    menuName: 'Home',
    title: 'Home',
    dockLabel: 'Home',
    icon: 'home',
    size: { w: 960, h: 620 },
    min: { w: 360, h: 380 },
    seamless: true,
  },
  weather: {
    id: 'weather',
    menuName: 'Weather',
    title: 'Weather — Kandy',
    dockLabel: 'Weather',
    icon: 'weather',
    size: { w: 1080, h: 640 },
    min: { w: 360, h: 380 },
    darkChrome: true,
  },
  pages: {
    id: 'pages',
    menuName: 'Pages',
    title: 'Résumé — M.R. Ahamed.pages',
    dockLabel: 'Pages',
    icon: 'pages',
    size: { w: 900, h: 620 },
    min: { w: 420, h: 380 },
  },
  numbers: {
    id: 'numbers',
    menuName: 'Numbers',
    title: 'Projects.numbers',
    dockLabel: 'Numbers',
    icon: 'numbers',
    size: { w: 900, h: 560 },
    min: { w: 420, h: 360 },
  },
  appstore: {
    id: 'appstore',
    menuName: 'App Store',
    title: 'App Store',
    dockLabel: 'App Store',
    icon: 'appstore',
    size: { w: 940, h: 600 },
    min: { w: 420, h: 380 },
  },
  tips: {
    id: 'tips',
    menuName: 'Tips',
    title: 'Tips',
    dockLabel: 'Tips',
    icon: 'tips',
    size: { w: 900, h: 620 },
    min: { w: 360, h: 360 },
  },
  facetime: {
    id: 'facetime',
    menuName: 'FaceTime',
    title: 'FaceTime',
    dockLabel: 'FaceTime',
    icon: 'facetime',
    size: { w: 820, h: 560 },
    min: { w: 380, h: 380 },
    darkChrome: true,
  },
  podcasts: {
    id: 'podcasts',
    menuName: 'Podcasts',
    title: 'Podcasts',
    dockLabel: 'Podcasts',
    icon: 'podcasts',
    size: { w: 960, h: 620 },
    min: { w: 380, h: 420 },
    seamless: true,
  },
  tv: {
    id: 'tv',
    menuName: 'TV',
    title: 'TV',
    dockLabel: 'TV',
    icon: 'tv',
    size: { w: 960, h: 600 },
    min: { w: 380, h: 380 },
    darkChrome: true,
    seamless: true,
  },
  books: {
    id: 'books',
    menuName: 'Books',
    title: 'Books',
    dockLabel: 'Books',
    icon: 'books',
    size: { w: 940, h: 620 },
    min: { w: 380, h: 420 },
    seamless: true,
  },
  stocks: {
    id: 'stocks',
    menuName: 'Stocks',
    title: 'Stocks',
    dockLabel: 'Stocks',
    icon: 'stocks',
    size: { w: 980, h: 600 },
    min: { w: 380, h: 420 },
    darkChrome: true,
    seamless: true,
  },
  journal: {
    id: 'journal',
    menuName: 'Journal',
    title: 'Journal',
    dockLabel: 'Journal',
    icon: 'journal',
    size: { w: 940, h: 640 },
    min: { w: 380, h: 420 },
    seamless: true,
  },
  freeform: {
    id: 'freeform',
    menuName: 'Freeform',
    title: 'Freeform — Untitled Board',
    dockLabel: 'Freeform',
    icon: 'freeform',
    size: { w: 960, h: 620 },
    min: { w: 380, h: 380 },
  },
  siri: {
    id: 'siri',
    menuName: 'Assistant',
    title: 'Portfolio Assistant',
    dockLabel: 'Assistant',
    icon: 'siri',
    size: { w: 420, h: 560 },
    min: { w: 320, h: 420 },
    darkChrome: true,
  },
  passwords: {
    id: 'passwords',
    menuName: 'Passwords',
    title: 'Passwords',
    dockLabel: 'Passwords',
    icon: 'passwords',
    size: { w: 820, h: 560 },
    min: { w: 380, h: 420 },
    seamless: true,
  },
  dictionary: {
    id: 'dictionary',
    menuName: 'Dictionary',
    title: 'Dictionary',
    dockLabel: 'Dictionary',
    icon: 'dictionary',
    size: { w: 860, h: 600 },
    min: { w: 380, h: 420 },
  },
  gamecenter: {
    id: 'gamecenter',
    menuName: 'Game Center',
    title: 'Game Center',
    dockLabel: 'Game Center',
    icon: 'gamecenter',
    size: { w: 1000, h: 680 },
    min: { w: 380, h: 480 },
    seamless: true,
  },
  webapp: {
    id: 'webapp',
    menuName: 'Web App',
    title: 'Web App',
    dockLabel: 'Web App',
    icon: 'safari',
    size: { w: 760, h: 540 },
    min: { w: 360, h: 380 },
  },
  hireme: {
    id: 'hireme',
    menuName: 'Hire Me',
    title: 'Hire M.R. Ahamed',
    dockLabel: 'Hire Me',
    icon: 'hireme',
    size: { w: 900, h: 640 },
    min: { w: 360, h: 440 },
    seamless: true,
  },
  casestudies: {
    id: 'casestudies',
    menuName: 'Case Studies',
    title: 'Case Studies',
    dockLabel: 'Case Studies',
    icon: 'casestudies',
    size: { w: 1060, h: 700 },
    min: { w: 380, h: 460 },
    seamless: true,
  },
  askai: {
    id: 'askai',
    menuName: 'Ask Me AI',
    title: 'Ask Me AI',
    dockLabel: 'Ask Me AI',
    icon: 'askai',
    size: { w: 760, h: 620 },
    min: { w: 360, h: 440 },
    seamless: true,
  },
  guestbook: {
    id: 'guestbook',
    menuName: 'Guestbook',
    title: 'Guestbook',
    dockLabel: 'Guestbook',
    icon: 'guestbook',
    size: { w: 860, h: 640 },
    min: { w: 360, h: 440 },
    seamless: true,
  },
  wallet: {
    id: 'wallet',
    menuName: 'Wallet',
    title: 'Wallet',
    dockLabel: 'Wallet',
    icon: 'wallet',
    size: { w: 860, h: 600 },
    min: { w: 360, h: 440 },
    seamless: true,
  },
  whatsapp: {
    id: 'whatsapp',
    menuName: 'WhatsApp',
    title: 'WhatsApp',
    dockLabel: 'WhatsApp',
    icon: 'whatsapp',
    size: { w: 940, h: 640 },
    min: { w: 360, h: 440 },
    seamless: true,
  },
  telegram: {
    id: 'telegram',
    menuName: 'Telegram',
    title: 'Telegram',
    dockLabel: 'Telegram',
    icon: 'telegram',
    size: { w: 940, h: 640 },
    min: { w: 360, h: 440 },
    seamless: true,
  },
  xapp: {
    id: 'xapp',
    menuName: 'X',
    title: 'X',
    dockLabel: 'X',
    icon: 'xapp',
    size: { w: 980, h: 680 },
    min: { w: 360, h: 440 },
    seamless: true,
  },
  yahoomail: {
    id: 'yahoomail',
    menuName: 'Yahoo Mail',
    title: 'Yahoo Mail',
    dockLabel: 'Yahoo Mail',
    icon: 'yahoomail',
    size: { w: 1020, h: 660 },
    min: { w: 380, h: 440 },
    seamless: true,
  },
  services: {
    id: 'services',
    menuName: 'My Services',
    title: 'Expertise & Capabilities',
    dockLabel: 'My Services',
    icon: 'services',
    size: { w: 1060, h: 700 },
    min: { w: 360, h: 460 },
    seamless: true,
  },
  sysprefs: {
    id: 'sysprefs',
    menuName: 'System Preferences',
    title: 'System Preferences',
    dockLabel: 'System Preferences',
    icon: 'sysprefs',
    size: { w: 780, h: 640 },
    min: { w: 360, h: 380 },
  },
  activity: {
    id: 'activity',
    menuName: 'Activity Monitor',
    title: 'Activity Monitor',
    dockLabel: 'Activity Monitor',
    icon: 'activity',
    size: { w: 860, h: 560 },
    min: { w: 380, h: 380 },
  },
  stickies: {
    id: 'stickies',
    menuName: 'Stickies',
    title: 'Stickies',
    dockLabel: 'Stickies',
    icon: 'stickies',
    size: { w: 720, h: 520 },
    min: { w: 320, h: 320 },
  },
  timemachine: {
    id: 'timemachine',
    menuName: 'Time Machine',
    title: 'Time Machine',
    dockLabel: 'Time Machine',
    icon: 'timemachine',
    size: { w: 860, h: 600 },
    min: { w: 420, h: 420 },
    seamless: true,
  },
  mirroring: {
    id: 'mirroring',
    menuName: 'iPhone Mirroring',
    title: 'iPhone Mirroring',
    dockLabel: 'iPhone Mirroring',
    icon: 'mirroring',
    size: { w: 440, h: 900 },
    min: { w: 300, h: 560 },
    seamless: true,
  },
  learning: {
    id: 'learning',
    menuName: 'Learning Hub',
    title: 'Learning Hub',
    dockLabel: 'Learning Hub',
    icon: 'learning',
    size: { w: 980, h: 620 },
    min: { w: 360, h: 420 },
    seamless: true,
  },
  flashcards: {
    id: 'flashcards',
    menuName: 'Flashcards & Quiz',
    title: 'Flashcards & Quiz',
    dockLabel: 'Flashcards & Quiz',
    icon: 'flashcards',
    size: { w: 940, h: 620 },
    min: { w: 340, h: 420 },
    seamless: true,
  },
  focusplanner: {
    id: 'focusplanner',
    menuName: 'Focus Planner',
    title: 'Focus Planner',
    dockLabel: 'Focus Planner',
    icon: 'focusplanner',
    size: { w: 900, h: 620 },
    min: { w: 340, h: 420 },
    seamless: true,
  },
  goals: {
    id: 'goals',
    menuName: 'Goals & Tasks',
    title: 'Goals & Tasks',
    dockLabel: 'Goals & Tasks',
    icon: 'goals',
    size: { w: 1000, h: 640 },
    min: { w: 340, h: 420 },
    seamless: true,
  },
  bizplanner: {
    id: 'bizplanner',
    menuName: 'Business Planner',
    title: 'Business Planner',
    dockLabel: 'Business Planner',
    icon: 'bizplanner',
    size: { w: 1020, h: 660 },
    min: { w: 340, h: 420 },
    seamless: true,
  },
  playground: {
    id: 'playground',
    menuName: 'Code Playground',
    title: 'Code Playground',
    dockLabel: 'Code Playground',
    icon: 'playground',
    size: { w: 1040, h: 660 },
    min: { w: 340, h: 420 },
    seamless: true,
  },
  documents: {
    id: 'documents',
    menuName: 'Documents',
    title: 'Documents',
    dockLabel: 'Documents',
    icon: 'documents',
    size: { w: 960, h: 620 },
    min: { w: 340, h: 420 },
    seamless: true,
  },
  guidebook: {
    id: 'guidebook',
    menuName: 'Guidebook',
    title: 'Guidebook',
    dockLabel: 'Guidebook',
    icon: 'guidebook',
    size: { w: 1000, h: 680 },
    min: { w: 340, h: 420 },
    seamless: true,
  },
  whatsnew: {
    id: 'whatsnew',
    menuName: 'What’s New',
    title: 'What’s New',
    dockLabel: 'What’s New',
    icon: 'whatsnew',
    size: { w: 560, h: 620 },
    min: { w: 320, h: 380 },
    seamless: true,
  },
  translate: {
    id: 'translate',
    menuName: 'Translate',
    title: 'Translate',
    dockLabel: 'Translate',
    icon: 'translate',
    size: { w: 820, h: 520 },
    min: { w: 360, h: 400 },
  },
  fontbook: {
    id: 'fontbook',
    menuName: 'Font Book',
    title: 'Font Book',
    dockLabel: 'Font Book',
    icon: 'fontbook',
    size: { w: 860, h: 560 },
    min: { w: 380, h: 380 },
  },
  grapher: {
    id: 'grapher',
    menuName: 'Grapher',
    title: 'Grapher',
    dockLabel: 'Grapher',
    icon: 'grapher',
    size: { w: 860, h: 600 },
    min: { w: 380, h: 400 },
  },
  phone: { id: 'phone', menuName: 'Phone', title: 'Phone', dockLabel: 'Phone', icon: 'phoneapp', size: { w: 420, h: 640 }, min: { w: 320, h: 480 }, seamless: true },
  shortcuts: { id: 'shortcuts', menuName: 'Shortcuts', title: 'Shortcuts', dockLabel: 'Shortcuts', icon: 'shortcuts', size: { w: 760, h: 520 }, min: { w: 340, h: 380 }, seamless: true },
  chess: { id: 'chess', menuName: 'Chess', title: 'Chess', dockLabel: 'Chess', icon: 'chess', size: { w: 620, h: 680 }, min: { w: 340, h: 420 } },
  textedit: { id: 'textedit', menuName: 'TextEdit', title: 'Untitled', dockLabel: 'TextEdit', icon: 'textedit', size: { w: 640, h: 520 }, min: { w: 340, h: 300 } },
  colormeter: {
    id: 'colormeter',
    menuName: 'Digital Color Meter',
    title: 'Digital Color Meter',
    dockLabel: 'Digital Color Meter',
    icon: 'colormeter',
    size: { w: 520, h: 440 },
    min: { w: 340, h: 360 },
  },
  preview: {
    id: 'preview',
    menuName: 'Preview',
    title: cv.displayName,
    dockLabel: 'Preview — CV',
    icon: 'preview',
    size: { w: 640, h: 620 },
    min: { w: 340, h: 360 },
  },
};

/** System section of the Dock. */
export const DOCK_SYSTEM: AppId[] = ['about', 'hireme', 'safari', 'google', 'messages', 'mail', 'contacts', 'calendar', 'reminders', 'maps', 'photos'];
/** Portfolio / development section of the Dock. */
/** v10.2 — Xcode (My Portfolio), My Skills (Notes) and Achievements (Slides) are no longer pinned in the Dock; the apps stay in Launchpad, Spotlight and on the Desktop. */
export const DOCK_PORTFOLIO: AppId[] = ['terminal', 'music', 'clock', 'calculator', 'settings'];
/** All apps with a permanent Dock slot. */
export const DOCK_APPS: AppId[] = [...DOCK_SYSTEM, ...DOCK_PORTFOLIO];
